In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import random

random.seed(42)

In [5]:
dfbackup = pd.read_csv('P39-Financial-Data.csv')
df = dfbackup.copy()
df.head()

entry_id  age  pay_schedule  home_owner  income  months_employed  \
0   7629673   40     bi-weekly           1    3135                0   
1   3560428   61        weekly           0    3180                0   
2   6934997   23        weekly           0    1540                6   
3   5682812   40     bi-weekly           0    5230                0   
4   5335819   33  semi-monthly           0    3590                0   

   years_employed  current_address_year  personal_account_m  \
0               3                     3                   6   
1               6                     3                   2   
2               0                     0                   7   
3               6                     1                   2   
4               5                     2                   2   

   personal_account_y  ...  amount_requested  risk_score  risk_score_2  \
0                   2  ...               550       36200      0.737398   
1                   7  ...               600       30150      0.738510   
2                   1  ...               450       34550      0.642993   
3                   7  ...               700       42150      0.665224   
4                   8  ...              1100       53850      0.617361   

   risk_score_3  risk_score_4  risk_score_5  ext_quality_score  \
0      0.903517      0.487712      0.515977           0.580918   
1      0.881027      0.713423      0.826402           0.730720   
2      0.766554      0.595018      0.762284           0.531712   
3      0.960832      0.767828      0.778831           0.792552   
4      0.857560      0.613487      0.665523           0.744634   

   ext_quality_score_2  inquiries_last_month  e_signed  
0             0.380918                    10         1  
1             0.630720                     9         0  
2             0.531712                     7         0  
3             0.592552                     8         1  
4             0.744634                    12         0  

[5 rows x 21 columns]

In [6]:
df.drop('months_employed', axis=1, inplace=True)

In [8]:
df['personal_account_mo'] = (df.personal_account_m +(df.personal_account_y*12))

In [9]:
df.drop(['personal_account_m', 'personal_account_y'], axis=1, inplace=True)

In [10]:
df.head()

entry_id  age  pay_schedule  home_owner  income  years_employed  \
0   7629673   40     bi-weekly           1    3135               3   
1   3560428   61        weekly           0    3180               6   
2   6934997   23        weekly           0    1540               0   
3   5682812   40     bi-weekly           0    5230               6   
4   5335819   33  semi-monthly           0    3590               5   

   current_address_year  has_debt  amount_requested  risk_score  risk_score_2  \
0                     3         1               550       36200      0.737398   
1                     3         1               600       30150      0.738510   
2                     0         1               450       34550      0.642993   
3                     1         1               700       42150      0.665224   
4                     2         1              1100       53850      0.617361   

   risk_score_3  risk_score_4  risk_score_5  ext_quality_score  \
0      0.903517      0.487712      0.515977           0.580918   
1      0.881027      0.713423      0.826402           0.730720   
2      0.766554      0.595018      0.762284           0.531712   
3      0.960832      0.767828      0.778831           0.792552   
4      0.857560      0.613487      0.665523           0.744634   

   ext_quality_score_2  inquiries_last_month  e_signed  personal_account_mo  
0             0.380918                    10         1                   30  
1             0.630720                     9         0                   86  
2             0.531712                     7         0                   19  
3             0.592552                     8         1                   86  
4             0.744634                    12         0                   98

In [14]:
df = pd.get_dummies(df, prefix='pay_schedule', prefix_sep=':')

In [15]:
df.drop('pay_schedule:semi-monthly', axis=1, inplace=True)

In [16]:
df.columns

Index(['entry_id', 'age', 'home_owner', 'income', 'years_employed',
       'current_address_year', 'has_debt', 'amount_requested', 'risk_score',
       'risk_score_2', 'risk_score_3', 'risk_score_4', 'risk_score_5',
       'ext_quality_score', 'ext_quality_score_2', 'inquiries_last_month',
       'e_signed', 'personal_account_mo', 'pay_schedule:bi-weekly',
       'pay_schedule:monthly', 'pay_schedule:weekly'],
      dtype='object')

In [22]:
X = df.drop('e_signed',axis=1)
y = df[['e_signed']]
userid = df[['entry_id']]

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)
train_id = X_train[['entry_id']]
test_id = X_test[['entry_id']]
X_train = X_train.drop('entry_id', axis=1)
X_test = X_test.drop('entry_id', axis=1)

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
scaler = StandardScaler()

In [110]:
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train.iloc[:, :-3]), columns = X_train.iloc[:, :-3].columns.values, index = X_train.index.values)
X_test_scaled = pd.DataFrame(scaler.transform(X_test.iloc[:, :-3]), columns = X_test.iloc[:, :-3].columns.values, index = X_test.index.values)

In [111]:
X_train_scaled = pd.concat([X_train_scaled, X_train.iloc[:, -3:]], axis=1)
X_test_scaled = pd.concat([X_test_scaled, X_test.iloc[:, -3:]], axis=1)

In [112]:
X_train_scaled

age  home_owner    income  years_employed  current_address_year  \
2698  -1.597641    1.162089  2.270284        0.651523             -0.936948   
7514   0.510466   -0.860519 -0.308489        0.651523              0.512315   
12650  1.016412   -0.860519 -0.665733        1.093334             -0.936948   
5094  -0.332777   -0.860519 -0.361414       -0.232101             -0.936948   
5018   0.763439    1.162089 -0.341567       -0.232101             -0.936948   
...         ...         ...       ...             ...                   ...   
11284 -0.670074   -0.860519 -0.047172        2.418770              0.874631   
11964  1.269385    1.162089  3.068791       -0.232101             -0.212316   
5390  -0.923047   -0.860519  0.002445       -0.673912              0.150000   
860   -1.091695    1.162089  0.935250       -1.115724              2.323895   
15795 -0.923047    1.162089 -1.300834       -0.673912              1.599263   

       has_debt  amount_requested  risk_score  risk_score_2  risk_score_3  \
2698   0.511949         -0.508332   -1.930241     -0.264107      0.521042   
7514   0.511949         -0.652099   -0.682192     -0.661641      1.610914   
12650  0.511949         -0.795866   -1.255708     -0.199622      1.406255   
5094   0.511949          2.367001    0.976443      0.653773      1.425159   
5018   0.511949          0.354268   -1.819448     -0.837440     -0.750887   
...         ...               ...         ...           ...           ...   
11284  0.511949          0.354268   -0.105417     -1.729422      0.047408   
11964  0.511949          2.942068    2.120217      0.443757      0.276314   
5390   0.511949          0.354268    0.823288      0.760467      1.322829   
860    0.511949         -0.364566   -0.688709      0.138533      0.420562   
15795 -1.953321         -0.148916   -0.004400      0.752428     -0.834107   

       risk_score_4  risk_score_5  ext_quality_score  ext_quality_score_2  \
2698      -1.128877     -0.639225           0.028956            -1.392286   
7514      -0.098686      0.987289           0.505084            -0.200426   
12650      0.973524      0.600835           0.982160            -0.441256   
5094      -0.017775      0.069607           0.537544             1.265594   
5018      -2.460447     -2.124629          -1.483315            -0.750655   
...             ...           ...                ...                  ...   
11284     -1.397896     -1.051443          -0.051770            -0.756010   
11964      0.863205      1.452318           0.979315             0.989541   
5390       0.550296      1.515109           1.284422             0.577134   
860       -0.079356      0.621027           1.614991            -0.526686   
15795     -0.895065     -1.826133           0.654882            -0.767787   

       inquiries_last_month  personal_account_mo  pay_schedule:bi-weekly  \
2698               0.149269             1.742054                       1   
7514               3.423198            -0.793974                       1   
12650              3.968853             1.742054                       1   
5094               0.422096             1.999955                       1   
5018              -0.396386            -0.321155                       0   
...                     ...                  ...                     ...   
11284             -1.214869            -0.149221                       1   
11964             -1.214869            -0.192205                       0   
5390              -1.214869            -0.836958                       1   
860               -1.214869             1.785037                       0   
15795             -0.396386             0.151663                       1   

       pay_schedule:monthly  pay_schedule:weekly  
2698                      0                    0  
7514                      0                    0  
12650                     0                    0  
5094                      0                    0  
5018                      1                  

# Model

## LogisticRegression

In [113]:
from sklearn.linear_model import LogisticRegression

In [114]:
logreg = LogisticRegression()
logreg.fit(X_train_scaled, y_train.values.ravel())

LogisticRegression()

In [175]:
y_pred = logreg.predict(X_test_scaled)

In [176]:
logreg.score(X_test_scaled, y_test)

0.5678391959798995

In [177]:
from sklearn.metrics import classification_report, confusion_matrix

In [178]:
print(confusion_matrix(y_test, y_pred))

[[ 676  976]
 [ 572 1358]]


In [179]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.54      0.41      0.47      1652
           1       0.58      0.70      0.64      1930

    accuracy                           0.57      3582
   macro avg       0.56      0.56      0.55      3582
weighted avg       0.56      0.57      0.56      3582



## Random Forest

In [126]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_scaled, y_train.values.ravel())

RandomForestClassifier()

In [168]:
y_pred2 = rf.predict(X_test_scaled)
rf.score(X_test_scaled, y_test)

0.6261864879955332

In [169]:
print(confusion_matrix(y_test, y_pred2))

[[ 944  708]
 [ 631 1299]]


In [170]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.60      0.57      0.59      1652
           1       0.65      0.67      0.66      1930

    accuracy                           0.63      3582
   macro avg       0.62      0.62      0.62      3582
weighted avg       0.63      0.63      0.63      3582



In [171]:
from sklearn.model_selection import cross_val_score
acc = cross_val_score(estimator = rf, X=X_train, y=y_train.values.ravel(), cv=10)

In [172]:
print(acc.mean(), acc.std()*2)

0.6213902057253797 0.019648999024784838


In [173]:
print(acc)

[0.62456385 0.62037683 0.60711793 0.62386602 0.60781577 0.60851361
 0.63407821 0.63337989 0.63058659 0.62360335]


In [174]:
from sklearn.model_selection import GridSearchCV

In [180]:
paramgrid = {'max_depth': [None],
            'max_features': [8, 10, 12],
            'min_samples_split': [2, 3, 4],
            'min_samples_leaf': [8, 10, 12],
            'bootstrap': [True],
            'criterion': ['gini']}

In [181]:
gcv = GridSearchCV(estimator=rf, param_grid=paramgrid, scoring = 'accuracy', cv=10, n_jobs = -1)

In [182]:
import time
t0 = time.time()
gcv.fit(X_train_scaled, y_train)
t1 = time.time()
print(t1-t0)

C:\Users\fadhl\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:880: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


189.5565106868744


In [183]:
gcv.best_score_

0.6333256012506481

In [184]:
gcv.best_params_

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 11,
 'min_samples_leaf': 7,
 'min_samples_split': 10}

In [185]:
y_pred3 = gcv.predict(X_test_scaled)
gcv.score(X_test_scaled, y_test.values.ravel())

0.632607481853713

In [186]:
print(confusion_matrix(y_test, y_pred3))

[[ 945  707]
 [ 609 1321]]


In [187]:
print(classification_report(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.61      0.57      0.59      1652
           1       0.65      0.68      0.67      1930

    accuracy                           0.63      3582
   macro avg       0.63      0.63      0.63      3582
weighted avg       0.63      0.63      0.63      3582



## Final Result

In [242]:
finalres = pd.concat([test_id, y_test], axis=1)

In [243]:
preddf = pd.DataFrame(y_pred3, columns=['predictions'], index=y_test.index.values)

In [244]:
finalres = pd.concat([finalres, preddf], axis=1)

In [245]:
finalres

entry_id  e_signed  predictions
3447    2325159         1            1
9696    3121330         1            1
2796    1186371         0            0
15689   2105203         1            0
10388   5368897         0            0
...         ...       ...          ...
4723    4525483         1            0
14800   4826515         0            1
8268    2749753         1            1
8807    3211238         1            1
11309   9760088         0            0

[3582 rows x 3 columns]

In [246]:
finalres['correct'] = np.where(finalres.e_signed == finalres.predictions, 1, 0)

In [247]:
finalres.correct.value_counts(normalize=True)

1    0.632607
0    0.367393
Name: correct, dtype: float64

In [248]:
finalres

entry_id  e_signed  predictions  correct
3447    2325159         1            1        1
9696    3121330         1            1        1
2796    1186371         0            0        1
15689   2105203         1            0        0
10388   5368897         0            0        1
...         ...       ...          ...      ...
4723    4525483         1            0        0
14800   4826515         0            1        0
8268    2749753         1            1        1
8807    3211238         1            1        1
11309   9760088         0            0        1

[3582 rows x 4 columns]